---
# tasks file for nginxhugo

- name: Install repository epel
  yum:
    name: epel-release
    state: present
- name: Install nginx
  yum:
    name: nginx
    state: present
  notify:
    - start_nginx
- name: allow firewalld
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
- name: Upload index.html
  copy:
    src: /etc/ansible/roles/nginxhugo/files/index.html
    dest: /usr/share/nginx/html
    mode: 0644
